# version: "3.8"

services:
  # Backend
  backend:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
    container_name: hackathon-backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: mongodb+srv://carlbrgs:xKcbcrj0TwiW4asW@tptwt.dj2ot.mongodb.net/buildup
      SERVER_PORT: 8080
      NODE_ENV: production
      CLIENT_URL: http://localhost:5173
    # depends_on:
    #  - mongodb
    networks:
      - hackathon-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    container_name: hackathon-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - hackathon-network
    restart: unless-stopped

  # Airflow

networks:
  hackathon-network:
    driver: bridge
